### ISSUE TITLE
Error during installation. Step: (Setup will now begin the installation. Continue? [Y/n])

### ISSUE THREAD

**Issue by ariellozanod** [EvernodeXRPL/evernode-host#176] opened 2024-01-19 23:25 UTC
![2024-01-19_17-17-21](https://github.com/EvernodeXRPL/evernode-host/assets/73303558/213c5afb-7ab9-4742-940f-047286fbbe66)

Hello !
An error occurs during installation as you can see in the image

_There was an error during installation. Please provide the file /tmp/evernode/installer-1705704924.log to Evernode team. Thank you._

My case is similar to: https://github.com/EvernodeXRPL/evernode-host/issues/149
I really want start to host so I'd rather solve the problem than the refund

At least we already checked that our address and balance are there:

![2024-01-19_19-14-32](https://github.com/EvernodeXRPL/evernode-host/assets/73303558/5d8753d5-1d32-4f41-bc7a-bc3eb320dec3)

This is our log file with the error specs
[installer-1705704924.log](https://github.com/EvernodeXRPL/evernode-host/files/13996031/installer-1705704924.log)

Thank you very much guys !

**Comment by vonstegen** [comment] 2024-01-20 20:15
For anyone else that experiences a similar issue to the one that I described, I have found a solution and posted it here:
https://github.com/EvernodeXRPL/evernode-host/issues/180#issuecomment-1902236147

**Comment by BimsaraFernando** [comment] 2024-03-19 04:49
Hi @ariellozanod , if the issue is already resolved, please close the issue.

After the latest Evernode Installer update release we have improved the installation script with bug fixes. Using the latest installation script will solve the issue. (https://github.com/EvernodeXRPL/evernode-host/issues/70#issuecomment-1976031300)  

If you are transferring the host registration, please follow the transfer guide (https://docs.evernode.org/en/latest/hosts/maintenance.html#transfer-the-host-registration )  
Thank you!

**Comment by BimsaraFernando** [comment] 2024-06-10 07:27
Hi @ariellozanod ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.

**Closed as completed by BimsaraFernando** 2024-06-10 07:27 UTC
