### ISSUE TITLE
Failed to stop sashimono-agent.service: Unit sashimono-agent.service not loaded.

### ISSUE THREAD

**Issue by herkimer9** [EvernodeXRPL/evernode-host#83] opened 2023-04-08 08:58 UTC
Hi, Thank you for giving me an advice for last problem

I have an another error about installation

I can see my server on evernode dashboard but it is inactive

It says "Failed to stop sashimono-agent.service: Unit sashimono-agent.service not loaded..."

I send you a file 

Thankt you always...! 

[installer-1680933666.log](https://github.com/EvernodeXRPL/evernode-host/files/11182863/installer-1680933666.log)

**Comment by ravinsp** [comment] 2023-04-08 09:34
Seems the actual offending line is: 
```
Invalid Sashimono Agent config creation args.
0, 5, 800000, 2744800, 0, 0
```
The last 0, 0 indicates the detected swap and disk space size which should have caused the setup to prevent starting the installation in the first place. Bit weird seeing this.

To further investigate this, can you post the output of the `free` and `df`  linux commands here?

Also, at the very beginning of the setup (just after you confirmed the very first 'Continue?' prompt), did you see a notice `System check complete. Your system is capable of becoming an Evernode beta host.`? (If you don't remember, you can run the setup again and press ctrl+C to exit the setup after you see the notice)

**Comment by herkimer9** [comment] 2023-04-08 11:03
This is my output of` free`and`df`

`free`
              total        used        free      shared  buff/cache   available
Mem:        3431028     1410608      124140        9108     1896280     1755980
swap:     3998716       21760     3976956
`df`
Filesystem     1K-blocks    Used Available Use% Mounted on
udev             1674992       0   1674992   0% /dev
tmpfs             343104    1724    341380   1% /run
/dev/sda3       55319776 9977620  42499584  20% /
tmpfs            1715512       0   1715512   0% /dev/shm
tmpfs               5120       4      5116   1% /run/lock
tmpfs            1715512       0   1715512   0% /sys/fs/cgroup
/dev/loop0           128     128         0 100% /snap/bare/5
/dev/loop2        119680  119680         0 100% /snap/core/14946
/dev/loop1         45696   45696         0 100% /snap/certbot/2913
/dev/loop5        254848  254848         0 100% /snap/gnome-3-38-2004/99
/dev/loop3         66816   66816         0 100% /snap/gtk-common-themes/1519
/dev/loop4         63488   63488         0 100% /snap/core20/1328
/dev/loop7         93952   93952         0 100% /snap/gtk-common-themes/1535
/dev/loop6        358144  358144         0 100% /snap/gnome-3-38-2004/137
/dev/loop9         55552   55552         0 100% /snap/snap-store/558
/dev/loop8         47104   47104         0 100% /snap/snap-store/638
/dev/loop10        51072   51072         0 100% /snap/snapd/18596
/dev/loop11        64896   64896         0 100% /snap/core20/1852
/dev/sda2        1994928    6216   1988712   1% /boot/efi
tmpfs             343100      60    343040   1% /run/user/1000
tmpfs             343100       8    343092   1% /run/user/1001

**Comment by kithminisg** [comment] 2023-04-10 07:31
@herkimer9, During your first attempt also, did you allocate the resources manually?

**Comment by kithminisg** [comment] 2023-04-10 10:43
Regarding the country code issue, we have found that the domain name supplied (`evernode3.xyz`) is associated with two IP addresses (One of them maps to `US`). In Evernode platform, it is recommended that each host is allocated a unique domain name. We are grateful for your feedback and plan to include domain validation in an upcoming release.

**Comment by kithminisg** [comment] 2023-04-10 12:04
@herkimer9 , When you execute the `free` command on your VM, is the output for the swap space listed with an uppercase "S" or a lowercase "s"? Actually, we noticed it as 's' as per the given [text](https://github.com/EvernodeXRPL/evernode-host/issues/83#issuecomment-1500867950).

**Comment by herkimer9** [comment] 2023-04-11 07:38
> @herkimer9, During your first attempt also, did you allocate the resources manually?

I didn't allocate it manually during first attempt

**Comment by herkimer9** [comment] 2023-04-11 07:49
> @herkimer9 , When you execute the `free` command on your VM, is the output for the swap space listed with an uppercase "S" or a lowercase "s"? Actually, we noticed it as 's' as per the given [text](https://github.com/EvernodeXRPL/evernode-host/issues/83#issuecomment-1500867950).

Actually It is uppercase 'S'. I changed the letter to show you because it appears as Korean.

**Comment by kithminisg** [comment] 2023-04-11 08:22
@herkimer9, Could you please attach a screenshot of the original command output here?

**Comment by herkimer9** [comment] 2023-04-13 21:34
> @herkimer9, Could you please attach a screenshot of the original command output here?
![Screenshot from 2023-04-14 06-32-51](https://user-images.githubusercontent.com/130145329/231887885-b424c30f-f8a6-4754-a8ec-957e4a6b60d0.png)

**Comment by ravinsp** [comment] 2023-04-16 05:07
@herkimer9 We were under the impression that for you the command outputs appear in Korean (since you mentioned such in an earlier comment). But in this screenshot, all outputs are in English.
We want to investigate whether our setup is misbehaving due to non-English language being used on the host.

**Comment by herkimer9** [comment] 2023-04-17 11:25
> @herkimer9우리는 당신에게 명령 출력이 한국어로 나타난다는 인상을 받았습니다(당신이 이전 코멘트에서 언급했기 때문에). 하지만 이 스크린샷에서는 모든 출력이 영어로 되어 있습니다.
> 호스트에서 영어가 아닌 언어가 사용되어 설정이 오작동하는지 여부를 조사하고자 합니다.

I changed system language to show you!

**Comment by herkimer9** [comment] 2023-04-26 13:07
> Thanks @herkimer9. May I suggest you try uninstalling and installing again with the system language set as English? I suspect our setup is tripping out due to some internal command output being in non-English. At the very least we can document that installer only supports English. Let us know here how it went with English as the system language. Thank you.

I uninstall and install again as you said and it works. Now I can see my swap memory size.
Thank you !!

**Comment by chalith** [comment] 2023-05-02 03:42
Good to here @herkimer9. Since now you have resolved the issue I will close this.

**Closed by chalith** 2023-05-02 03:42 UTC
