### ISSUE TITLE
Error occured when retrieving account info.

### ISSUE THREAD

**Issue by TheMainlander** [EvernodeXRPL/evernode-host#66] opened 2022-12-08 10:40 UTC
Can't get my host back up.

---
Registry address: r3cNR2bdao1NyvQ5ZuQvCUgqkoWGmgF34E
Host account address: rsvqcL64dHCX7TACtk8SM6fhAVxFJypyNB
Error occured when retrieving account info.
Evernode xrpl message board exiting with error.

**Comment by ravinsp** [comment] 2022-12-08 12:53
@TheMainlander was this an installation that was running normally and suddenly 'evernode status' command showing this error? or did you attempt to uninstall and install evernode?

**Comment by kithminisg** [comment] 2022-12-08 14:08
@TheMainlander , It seems your host has been pruned due to its inactivity. Hence, you have to uninstall and re-install Evernode.

Note: You have to use an EVR-funded XRPL Account secret for your next installation. [Get an EVR-funded Account](https://dashboard.evernode.org/#/testnet-faucet)

FYR

![image](https://user-images.githubusercontent.com/18496375/206466385-226d9a58-aa80-44dd-9d28-db19b57ddfe2.png)

**Comment by chalith** [comment] 2022-12-14 03:44
Closing since the issue is resolved

**Closed by chalith** 2022-12-14 03:44 UTC

**Comment by TheMainlander** [comment] 2022-12-30 04:55
Just uninstalled. 

FYI:
---

**Evernode xrpl message board exiting with error.
Evernode host deregistration failed. Still do you want to continue uninstall?**

---
Uninstalling...
---Sashimono uninstaller---
Removed /home/sashimbxrpl/.config/systemd/user/default.target.wants/sashimono-mb-xrpl.service.
Removing Sashimono cgroup creation service...
Removed /etc/systemd/system/multi-user.target.wants/sashimono-cgcreate.service.
Removing Sashimono service...
Removed /etc/systemd/system/multi-user.target.wants/sashimono-agent.service.
Removing Sashimono private docker registry...
sashidockerreg does not exist.
Deleting binaries...
Deleting Sashimono CLI...
Deleting data directory...
Deleting cgroup rules...
Restarting the 'cgrulesengd' service...
Attempting Evernode host deregistration...
Deregistering host...
Transaction result: tesSUCCESS
Burnt unsold hosting NFT (00010000201EDFE233210364FC4044F416BBDF058BED8B0A6A3D14B60000001B) of rsvqcL64dHCX7TACtk8SM6fhAVxFJypyNB account
Transaction result: tesSUCCESS
Burnt unsold hosting NFT (00010000201EDFE233210364FC4044F416BBDF058BED8B0A8122E5B70000001C) of rsvqcL64dHCX7TACtk8SM6fhAVxFJypyNB account
Transaction result: tesSUCCESS
Burnt unsold hosting NFT (00010000201EDFE233210364FC4044F416BBDF058BED8B0A9808B6B80000001D) of rsvqcL64dHCX7TACtk8SM6fhAVxFJypyNB account
Host not registered.
Evernode xrpl message board exiting with error.
Evernode host deregistration failed. Still do you want to continue uninstall? [Y/n] y

**Comment by TheMainlander** [comment] 2022-12-30 05:03
Ok, there are a lot of changes here!

1. I now need a Domain!
2. I need to specify a Rate that I had not considered!
3. Set "wss://hooks-testnet-v2.xrpl-labs.com'" which I would expect should be a "Yes" and I did

I admit I have not been here for a while ... is there a Product Manager friendly Guide rather than a 7337 Dev guide available, please!? :)

**Comment by TheMainlander** [comment] 2022-12-30 05:12
My apologies, @chalith @kithminisg thank you for the help! :)
