### ISSUE TITLE
How to restore the inactive node or re-install (the instructions in Cli are very vague)

### ISSUE THREAD

**Issue by EpicShah** [EvernodeXRPL/evernode-host#166] opened 2024-01-18 14:32 UTC
anyway, not here to waste my time arguing about it, so while restoring and reinstalling it asks me to specify the xahau host address when i set the same address it says account already registered. So how the heck am i supposed to re-install whitout losing 500 Evrs
![ever1](https://github.com/EvernodeXRPL/evernode-host/assets/123892683/dc7cb11f-aebd-472b-8f74-603915357c64)

**Comment by EpicShah** [comment] 2024-01-18 14:33
![ever2](https://github.com/EvernodeXRPL/evernode-host/assets/123892683/1df4170f-4485-474b-ad2a-b68329e3241b)

**Comment by Thopfi** [comment] 2024-01-18 17:03
HI!
I had the same problem and now solved.
Look @ my thread:

https://github.com/EvernodeXRPL/evernode-host/issues/144

**Comment by chalith** [comment] 2024-01-19 05:06
@EpicShah If it's saying you are already registered you can transfer the registration with https://docs.evernode.org/en/latest/hosts/maintenance.html#transfer-the-host-registration (Run the command starting with curl on another machine). Then try re installing with the same account.

**Comment by EpicShah** [comment] 2024-01-19 22:29
thanks bro @Thopfi

**Comment by lendlycagata** [comment] 2024-01-29 15:50
@chalith when I transfer my host it was asking for Specify the path of the Host Account secret: { "xrpl": { "secret": "my secret here" } } and return invalid path,. how to get around with this?

**Comment by BimsaraFernando** [comment] 2024-06-11 05:02
Hi @lendlycagata ,
we are closing the issue assuming the issue is resolved by now. If not please refer this https://docs.evernode.org/en/latest/hosts/maintenance.html#transfer-the-host-registration .

**Closed as completed by BimsaraFernando** 2024-06-11 05:02 UTC
Labels: update-failure
