### ISSUE TITLE
Inactive Host >> Transfer >> Failed installation

### ISSUE THREAD

**Issue by EpicShah** [EvernodeXRPL/evernode-host#210] opened 2024-01-22 02:41 UTC
almost repeated the steps several times with transfer and install subsequently but the got the REG-FAILURE error

"type": "response"
}
Evernode Xahau message board exiting with error.
REG_FAILURE
Rolling back sashimono installation.

curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s install

curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s transfer

**Comment by EpicShah** [comment] 2024-01-22 02:45
Configuaring host setup on Evernode...
STAGE Configuring host Xahau account
Using registry: rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
STAGE Configuring Sashimono services
Creating cgroup rules...
Restarting the 'cgrulesengd' service.
Configuring sashimono agent service...
Config file created at /etc/sashimono/sa.cfg
Created symlink /etc/systemd/system/multi-user.target.wants/sashimono-cgcreate.service → /etc/systemd/system/sashimono-cgcreate.service.
Created symlink /etc/systemd/system/multi-user.target.wants/sashimono-agent.service → /etc/systemd/system/sashimono-agent.service.
Installing Evernode Xahau message board...
Updated mb user .bashrc.
STAGE Configuring Xahau message board service
Created symlink /home/sashimbxrpl/.config/systemd/user/default.target.wants/sashimono-mb-xrpl.service → /home/sashimbxrpl/.config/systemd/user/sashimono-mb-xrpl.service.
Installed Evernode Xahau message board.
Registering host on Evernode...
STAGE Registering host on Evernode registry rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
Executing register with params: BG 800000 3211120 2516560 17565200 6                 Intel(R)_Xeon(R)_CPU_E5-2650_0_2.00GHz 2 1995 ***** _
Registering host...
Burning unsold URITokens related to the previous leases.
sell offer
Transaction result: tesSUCCESS
Waiting for the sell offer 1D87617433F5E0E140D95075C6B1C70E1A470906F21741B5D4730FCF2EB8EE14
Accepting the sell offer..
Transaction result: tesSUCCESS
STAGE Creating lease offers for instance slots...
Offer lease NFT creation error.
Evernode Xahau message board exiting with error.
REG_FAILURE
Rolling back sashimono installation.
---Sashimono uninstaller---
Removed /home/sashimbxrpl/.config/systemd/user/default.target.wants/sashimono-mb-xrpl.service.
Removing Sashimono cgroup creation service...
Removed /etc/systemd/system/multi-user.target.wants/sashimono-cgcreate.service.
Removing Sashimono service...
Removed /etc/systemd/system/multi-user.target.wants/sashimono-agent.service.
Removing Sashimono private docker registry...
sashidockerreg does not exist.
Deleting binaries...
Deleting Sashimono CLI...
Deleting cgroup rules...
Restarting the 'cgrulesengd' service...
Deleting message board user...
Deleting binaries...
Cleaning up letsencrypt ssl certs for ''"
Deleted all files relating to certificate ""
Congratulations! You have successfully revoked the certificate that was located at /etc/letsencrypt/live/evernode06.********/cert.pem.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Cleaning up firewall rule for SSL validation
Rules updated
Rules updated (v6)
Account deactivated.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Deleting data directory...
Sashimono uninstalled successfully.
Rolled back the installation.

**Comment by shortthefomo** [comment] 2024-01-22 03:17
#206
#209 
#210 (this one)

why you do that?

**Comment by CallDrop** [comment] 2024-01-22 03:38
share the error log.

I am curious if we get the same error.

**Comment by EpicShah** [comment] 2024-01-22 03:41
the log is above

**Comment by EpicShah** [comment] 2024-01-22 03:43
STAGE Installing dependencies
Hit:1 http://bg.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://bg.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 http://bg.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:4 http://bg.archive.ubuntu.com/ubuntu focal-security InRelease
Hit:5 https://deb.nodesource.com/node_20.x nodistro InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
quota is already the newest version (4.05-1).
cgroup-tools is already the newest version (0.41-10).
fuse3 is already the newest version (3.9.0-2).
curl is already the newest version (7.68.0-1ubuntu2.21).
openssl is already the newest version (1.1.1f-1ubuntu2.20).
uidmap is already the newest version (1:4.8.1-1ubuntu5.20.04.4).
The following packages were automatically installed and are no longer required:
  libfwupdplugin1 libxmlb1
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
STAGE Configuring fstab
fstab already configured.
STAGE Configuring fuse
Fuse config already updated.
STAGE Configuring cgroup rules engine
STAGE Configuring grub
Grub already configured.
---Sashimono installer---
STAGE Setting up letsencrypt certbot
Rules updated
Rules updated (v6)
Running certbot certonly
Account registered.
Requesting a certificate for evernode06.kashdev.xyz

Successfully received certificate.
Certificate is saved at: /etc/letsencrypt/live/***/fullchain.pem
Key is saved at:         /etc/letsencrypt/live/***/privkey.pem
This certificate expires on 2024-04-21.
These files will be updated when the certificate renews.
Certbot has set up a scheduled task to automatically renew this certificate in the background.
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
If you like Certbot, please consider supporting our work by:
 * Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
 * Donating to EFF:                    https://eff.org/donate-le
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Setting up certbot deploy hook /etc/letsencrypt/renewal-hooks/deploy/sashimono-*****.sh
STAGE Installing docker packages
Installing rootless docker packages into /usr/bin/sashimono/dockerbin
Private docker registry installation skipped
Configuaring host setup on Evernode...
STAGE Configuring host Xahau account
Using registry: rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
STAGE Configuring Sashimono services
Creating cgroup rules...
Restarting the 'cgrulesengd' service.
Configuring sashimono agent service...
Config file created at /etc/sashimono/sa.cfg
Created symlink /etc/systemd/system/multi-user.target.wants/sashimono-cgcreate.service → /etc/systemd/system/sashimono-cgcreate.service.
Created symlink /etc/systemd/system/multi-user.target.wants/sashimono-agent.service → /etc/systemd/system/sashimono-agent.service.
Installing Evernode Xahau message board...
Updated mb user .bashrc.
STAGE Configuring Xahau message board service
Created symlink /home/sashimbxrpl/.config/systemd/user/default.target.wants/sashimono-mb-xrpl.service → /home/sashimbxrpl/.config/systemd/user/sashimono-mb-xrpl.service.
Installed Evernode Xahau message board.
Registering host on Evernode...
STAGE Registering host on Evernode registry rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
Executing register with params: BG 800000 3211120 2516560 17565200 6                 Intel(R)_Xeon(R)_CPU_E5-2650_0_2.00GHz 2 1995 ******* _
Registering host...
Burning unsold URITokens related to the previous leases.
sell offer
Transaction result: tesSUCCESS
Waiting for the sell offer 1D87617433F5E0E140D95075C6B1C70E1A470906F21741B5D4730FCF2EB8EE14
Accepting the sell offer..
Transaction result: tesSUCCESS
STAGE Creating lease offers for instance slots...
Offer lease NFT creation error.
Evernode Xahau message board exiting with error.
REG_FAILURE
Rolling back sashimono installation.
---Sashimono uninstaller---
Removed /home/sashimbxrpl/.config/systemd/user/default.target.wants/sashimono-mb-xrpl.service.
Removing Sashimono cgroup creation service...
Removed /etc/systemd/system/multi-user.target.wants/sashimono-cgcreate.service.
Removing Sashimono service...
Removed /etc/systemd/system/multi-user.target.wants/sashimono-agent.service.
Removing Sashimono private docker registry...
sashidockerreg does not exist.
Deleting binaries...
Deleting Sashimono CLI...
Deleting cgroup rules...
Restarting the 'cgrulesengd' service...
Deleting message board user...
Deleting binaries...
Cleaning up letsencrypt ssl certs for '*****'
Deleted all files relating to certificate *******.
Congratulations! You have successfully revoked the certificate that was located at /etc/letsencrypt/live/****/cert.pem.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Cleaning up firewall rule for SSL validation
Rules updated
Rules updated (v6)
Account deactivated.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Deleting data directory...
Sashimono uninstalled successfully.
Rolled back the installation.

**Comment by CallDrop** [comment] 2024-01-22 03:47
Looks like they have different root cause


**ok, you fail here:**

Transaction result: tesSUCCESS
Waiting for the sell offer 1D87617433F5E0E140D95075C6B1C70E1A470906F21741B5D4730FCF2EB8EE14
Accepting the sell offer..
Transaction result: tesSUCCESS
STAGE Creating lease offers for instance slots...
**Offer lease NFT creation error.**
Evernode Xahau message board exiting with error.
REG_FAILURE
Rolling back sashimono installation.

**I fail here:**

Transaction result: tesSUCCESS
Waiting for the sell offer A181C77FC0A2D16C17C07C16272E92565149DA499D514714C452A437BFA6CA09
Accepting the sell offer..
**The latest ledger sequence 2382555 is greater than the transaction's LastLedgerSequence (2382554).**
Evernode Xahau message board exiting with error.
REG_FAILURE
Rolling back sashimono installation.

**Comment by chalith** [comment] 2024-01-22 09:36
@EpicShah did you try transferring and reinstalling using this link https://docs.evernode.org/en/latest/hosts/maintenance.html#transfer-the-host-registration. Use the command starting with curl.
You will have your host secret in the default location if you haven't specified any.

**Comment by EpicShah** [comment] 2024-01-22 12:46
i did, i already said above, it works sometime but this time it didnt work, host getting the error above

**Comment by EpicShah** [comment] 2024-01-22 13:12
@chalith this is the lates fail log


REG_FAILURE
Rolling back sashimono installation.
---Sashimono uninstaller---
Removed /home/sashimbxrpl/.config/systemd/user/default.target.wants/sashimono-mb-xrpl.service.
Removing Sashimono cgroup creation service...
Removed /etc/systemd/system/multi-user.target.wants/sashimono-cgcreate.service.
Removing Sashimono service...
Removed /etc/systemd/system/multi-user.target.wants/sashimono-agent.service.
Removing Sashimono private docker registry...
sashidockerreg does not exist.
Deleting binaries...
Deleting Sashimono CLI...
Deleting cgroup rules...
grep: /etc/systemd/system/dbus-org.freedesktop.ModemManager1.service: No such file or directory
grep: /etc/systemd/system/dbus-org.freedesktop.nm-dispatcher.service: No such file or directory
Restarting the 'cgrulesengd' service...
Deleting message board user...
Deleting binaries...
Cleaning up letsencrypt ssl certs for 'evernode07.mustoodev.xyz'
Deleted all files relating to certificate evernode07.mustoodev.xyz.
Congratulations! You have successfully revoked the certificate that was located at /etc/letsencrypt/live/evernode07.mustoodev.xyz/cert.pem.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Cleaning up firewall rule for SSL validation
Rules updated
Rules updated (v6)
Account deactivated.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Deleting data directory...
Sashimono uninstalled successfully.
Rolled back the installation.
root@r~#

**Comment by chalith** [comment] 2024-01-23 06:09
@EpicShah it looks like your host is back in business again. There's a chance of failing transactions due to network load in some times I'm suspecting whether that's the cause for your previous failure.

**Comment by BimsaraFernando** [comment] 2024-06-10 07:30
Hi @EpicShah  ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.

**Closed as completed by BimsaraFernando** 2024-06-10 07:30 UTC
