### ISSUE TITLE
install fails as root with 'Permission denied'

### ISSUE THREAD

**Issue by jellicoe** [EvernodeXRPL/evernode-host#150] opened 2024-01-16 20:24 UTC
During install as root I get the following error in the log 

STAGE Configuring Xahau message board service
mkdir: cannot create directory ‘/home/sashimbxrpl/.config’: Permission denied
Message board user systemd folder creation failed
Rolling back sashimono installation.

also See folder - note .evernode-host folder was created by user 1001 rather than root

root@evernode01:/home/sashimbxrpl# ll
total 16
drwxr-xr-x 3 root root 4096 Jan 16 19:38 ./
drwxr-xr-x 6 root root 4096 Jan 16 02:15 ../
-rw-r--r-- 1 root root   86 Jan 16 20:05 .bashrc
dr-x------ 2 1001 1001 4096 Jan 16 02:15 .evernode-host/
root@evernode01:/home/sashimbxrpl#
and then only 250 EVR is refunded of the 500 registration fee

see TX 

500 Registration Fee
https://xahauexplorer.com/explorer/50B42B3D1AA9784CDE8732977D1C9104E1612617E893AF9DAC037C255FFF1E29

250 Refund
https://xahauexplorer.com/explorer/76C447D2208BA13386CEAC0C35EFA6BB77E2F3C10DBDCBC7C05981EF85318F18

cheers

**Comment by jellicoe** [comment] 2024-01-16 20:48
it could be something to do with sashimbxrpl .bashrc - it only has one export in it repeated twice 

root@evernode01:/home# cat sashimbxrpl/.bashrc

    export XDG_RUNTIME_DIR=/run/user/1001

    export XDG_RUNTIME_DIR=/run/user/1001

**Comment by jellicoe** [comment] 2024-01-16 21:52
I did a new build on a new Linux server and it worked fine

this 'Permission denied' issue is happening on my old Beta v3 server 

i'm guessing the xahau installation has issues with the existing /home/sashimbxrpl folder I used on Beta 3 ??

**Comment by chalith** [comment] 2024-01-17 07:27
Yes, Your guess is correct. The directory created by old installation cannot be accessed by new user. We found a fix for that and will be releasing it in our next release.
And you will be getting a refund of your lost EVRs

**Comment by jellicoe** [comment] 2024-01-17 07:39
thank you sir - I hope you can get some sleep one day - you guys are doing great work

**Comment by chalith** [comment] 2024-01-19 09:56
@jellicoe hope you received the refund and the issue is resolved. Shall I close the issue?

**Comment by jellicoe** [comment] 2024-01-19 10:04
yes sir, I started new node and refund came to other address that had issues - all resolved now  - all is good - you are the best man @ScottChamberlain @chalith is awesome - this whole airdrop and node rally on xahau has been a lot of fun and xaman (weitse) is so awesome - most fun i've had for a while - we love you @chalith

**Comment by chalith** [comment] 2024-01-26 07:35
@jellicoe Thank you. We appreciate you trusting us and being with Evernode. If you have any doubts reach us any time. Closing the issue as now resolved.

**Closed as completed by chalith** 2024-01-26 07:35 UTC
Labels: installation-error, installation-error-permission-denied
