### ISSUE TITLE
error code - 1706360566.log

### ISSUE THREAD

**Issue by cOoNni** [EvernodeXRPL/evernode-host#267] opened 2024-01-27 13:09 UTC
what sould i do solve this error ,,TT

![1706-2](https://github.com/EvernodeXRPL/evernode-host/assets/157492996/133a3c7f-f740-4887-8f4b-4e3ac1c1870c)

**Comment by LexBulk** [comment] 2024-01-27 14:57
look here, I described everything, I had such errors https://github.com/EvernodeXRPL/evernode-host/issues/265#issue-2103528946

**Comment by BimsaraFernando** [comment] 2024-03-14 10:22
Hi, if the issue is already resolved, please close the issue.
If you are transferring the host registration, please follow the transfer guide (https://docs.evernode.org/en/latest/hosts/maintenance.html#transfer-the-host-registration )  
Thank you.

**Comment by BimsaraFernando** [comment] 2024-06-10 07:50
Hi @cOoNni ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.

**Closed as completed by BimsaraFernando** 2024-06-10 07:50 UTC
