### ISSUE TITLE
Inactive node error 

### ISSUE THREAD

**Issue by QRSK01** [EvernodeXRPL/evernode-host#198] opened 2024-01-21 08:14 UTC
Hello everyone, tell me, yesterday I installed the node, some kind of error occurred, the black screen disappeared, they charged a registration fee, the node appears inactive on the website, I can’t find the logs in the server and when I respond to the evernode status command it returns command no found. 
wallet registered when installing the node:
rKKqPJm7EbUSUkKjLKWhG33sXy9i5LS6bZ

**Comment by BimsaraFernando** [comment] 2024-03-19 05:02
Hi, @QRSK01,
 it seems like your server is up and running. are you still facing any issues?
If the issue is resolved, please close the issue.
Thank you!

**Comment by BimsaraFernando** [comment] 2024-03-19 05:03
After the latest Evernode Installer update release we have improved the installation script with bug fixes. Using the latest installation script will solve the issue. (https://github.com/EvernodeXRPL/evernode-host/issues/70#issuecomment-1976031300)  

If you are transferring the host registration, please follow the transfer guide (https://docs.evernode.org/en/latest/hosts/maintenance.html#transfer-the-host-registration )

**Comment by BimsaraFernando** [comment] 2024-06-10 07:29
Hi @QRSK01 ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.

**Closed as completed by BimsaraFernando** 2024-06-10 07:29 UTC
