### ISSUE TITLE
Unsuccessful Installation

### ISSUE THREAD

**Issue by lendlycagata** [EvernodeXRPL/evernode-host#335] opened 2024-02-20 00:45 UTC
error: There was an error during installation. Please provide the file /tmp/evernode/installer-1708388213.log to Evernode team. Thank you.

address : rw7sNZ6P39qeT4tmHP9CxUrPc2NtBf1goU

Host not registered

**Comment by BimsaraFernando** [comment] 2024-03-14 07:43
Hi, it seems like your host rw7sNZ6P39qeT4tmHP9CxUrPc2NtBf1goU is up and running. If the problem is resolved, please close the issue.
Thank you!

**Comment by BimsaraFernando** [comment] 2024-06-10 11:11
@lendlycagata ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.

**Closed as completed by BimsaraFernando** 2024-06-10 11:11 UTC
