### ISSUE TITLE
Installation error => Completed normally. oh my god. thank you

### ISSUE THREAD

**Issue by BLUEDIAA** [EvernodeXRPL/evernode-host#313] opened 2024-02-09 05:43 UTC
Downloading Environment configuration...

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   655  100   655    0     0   4612      0 --:--:-- --:--:-- --:--:--  4612

Checking Evernode mainnet environment details...
Downloading setup support files...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  880k  100  880k    0     0  2904k      0 --:--:-- --:--:-- --:--:-- 2904k
Done.

Do you want to connect to the default rippled server (wss://xahau.network)? [Y/n]y

Checking server wss://xahau.network...
Using Rippled server 'wss://xahau.network'.

Specify the Xahau account address: rwR49GA9sVMLGBUir2mTVz7WheXTUQGBWF
Checking account rwR49GA9sVMLGBUir2mTVz7WheXTUQGBWF...
Host is not registered.
Specify the Xahau account address: rwR49GA9sVMLGBUir2mTVz7WheXTUQGBWF
Checking account rwR49GA9sVMLGBUir2mTVz7WheXTUQGBWF...
Host is not registered.
Specify the Xahau account address:

**Comment by BLUEDIAA** [comment] 2024-02-09 06:31
I will summarize the successful installation procedure and post it separately.

**Comment by BimsaraFernando** [comment] 2024-03-14 08:00
Hi, it seems the issue is resolved.
We are closing the issue.

**Closed as completed by BimsaraFernando** 2024-03-14 08:00 UTC
