### ISSUE TITLE
Evernode host got purged / Evernode host doesn't update

### ISSUE THREAD

**Issue by xVet** [EvernodeXRPL/evernode-host#71] opened 2023-01-08 01:28 UTC
Hi there,

i have the following issue:

My evernode host 1: https://dashboard.evernode.org/#/host/rGorZwDBfkBZkzhatECE3NkkzAt4zC3gmx (dont wonder about the evers, i moved the them in an attempt to re register) is displayed as inactive. Checking the server, i had to conclude the daemon is purged. None of the evernode commands work. Generating a logfile from syslog resulted in a empty file. Sashimono directory is available.

My evernode host 2: https://dashboard.evernode.org/#/host/rGimyJdP7Lq79fHi3PhYnrgjUWLe9262Q3 , is in the same situation with the important difference that the evernode daemon is available and running. I can execute evernode commands and i also updated via "evernode update" , resulting in a positive prompt. But, the dashboard shows my host is offline/inactive.

A log file for evernode host 2:

[mydebug.log](https://github.com/EvernodeXRPL/evernode-host/files/10367521/mydebug.log)

Thank you in advance!

**Comment by ravinsp** [comment] 2023-01-08 03:57
@xVet Thank you very much for digging into this.

Regarding host 1, I don't have a clue yet and we'll get back to you on that with more things to try.

On host 2, since the 'evernode' command is functional on that host, please post the log file generated from `sudo evernode log` command. That might contain more clues. Thanks.

**Comment by xVet** [comment] 2023-01-08 13:05
Thank you @ravinsp !

For host 2 i attached here the log generated with `sudo evernode log` :

[evernode.JR6P2Nuwz.log](https://github.com/EvernodeXRPL/evernode-host/files/10368470/evernode.JR6P2Nuwz.log)

**Comment by chalith** [comment] 2023-01-09 04:38
@xVet you can find the temporary log files inside `/tmp/evernode-beta/` directory which are created on the installation. Run `ls -l /tmp/evernode-beta/` and find the files which are created on `Jan  4`. Then can you send us the files.

**Comment by xVet** [comment] 2023-01-09 09:27
@chalith i attached the log files created on `Jan 4`

Host 1:  
[installer-1672834475.log](https://github.com/EvernodeXRPL/evernode-host/files/10371902/installer-1672834475.log)


Host 2:

[installer-1672834874.log](https://github.com/EvernodeXRPL/evernode-host/files/10371905/installer-1672834874.log)

**Comment by chalith** [comment] 2023-01-10 06:15
@xVet it seems for the Host 1, there was a bug in v0.5.20 release which has crashed the update process. You can follow these steps to reinstall a host with the same xrpl account, so you won't loose your EVRs.
 
- First, execute `cat /etc/sashimono/mb-xrpl/mb-xrpl.cfg` and note down the `address` value.
- Then execute `cat /etc/sashimono/mb-xrpl/secret.cfg` and note down the `secret` value.
- Then download [transfer.zip](https://github.com/EvernodeXRPL/evernode-host/files/10379408/transfer.zip), extract and execute `node transfer` from any machine which has node js installed, This will prompt for host address and secret which you have previously noted down. 
- Then run `curl -fsSL https://stevernode.blob.core.windows.net/evernode-beta/setup.sh | cat | sudo bash -s uninstall` to remove current sashimono files. This might end up with errors but do not worry about it.
- Then install evernode again. Give the above noted address and secret for the host when installing.

BTW, we are still investigating on what went wrong in Host 2. We'll get back to you when we figure out the cause.

**Comment by xVet** [comment] 2023-01-10 11:54
Thanks a lot guys! well done! 

I attempted to follow your instructions, when i re installed evernode i got the prompt that an error occured during installation and that i should contact you guys with the log file.

So heres the log file ( reinstall attempt on Host 1 ):

[installer-1673345431.log](https://github.com/EvernodeXRPL/evernode-host/files/10382385/installer-1673345431.log)

**Comment by chalith** [comment] 2023-01-11 05:19
@xVet looks like you are running a nginx server in `evernode2.xrp.vet` domian which you have pointed to the host. As it's mentioned [here](https://github.com/EvernodeXRPL/evernode-host#domain-name) ssl validations fails since nginx is listening on port 80.

- You can stop the nginx server before installing evernode and then install the evernode
- After installing evernode you can start the ngnx again

**Comment by chalith** [comment] 2023-01-11 09:45
> @xVet looks like you are running a nginx server in `evernode2.xrp.vet` domian which you have pointed to the host. As it's mentioned [here](https://github.com/EvernodeXRPL/evernode-host#domain-name) ssl validations fails since nginx is listening on port 80.
> 
> * You can stop the nginx server before installing evernode and then install the evernode
> * After installing evernode you can start the ngnx again

@xVet about the starting the nginx again, Evernode automatically updates the SSL certificates in 3 months when they are expired. So if the nginx is running using the domain it would cause an issue when the SSL renewal happens

**Comment by xVet** [comment] 2023-01-11 14:07
Thank you @chalith , i just let nginx to listen to 443 (ssl) and the whole installation went through without a problem! 

Host 1 is looking good again per: https://dashboard.evernode.org/#/host/rGorZwDBfkBZkzhatECE3NkkzAt4zC3gmx

**Comment by chalith** [comment] 2023-01-12 06:18
@xVet Can you please run `evernode log` on Host 2 again and send us the output file.

**Comment by xVet** [comment] 2023-01-13 12:40
@chalith sorry for the delay!

Heres the log generated with `evernode log` for Host 2: 

[evernode.miEhzDNGs.log](https://github.com/EvernodeXRPL/evernode-host/files/10411584/evernode.miEhzDNGs.log)

**Comment by mezmac** [comment] 2023-01-14 15:36
What exactly is the node transfer js doing? Can whatever it's accomplishing be done manually? (Sorry, I'm trying to look at the code from my phone, and it's difficult to view). Trying to understand. Thanks.

**Comment by ravinsp** [comment] 2023-01-14 17:07
@mezmac It basically places your existing registration on the registry into the "transfer" mode which indicates that the existing host registration is ready to be handed over to a new host installation. In this case, you need to do this you can reinstall to fix your broken host and the new installation to be able to take over your existing registration on the registry.

(Normally this "transfer" feature is intended to be used by functioning hosts so they can migrate their host to a new machine or to a different account. But here we are using it as a workaround to fix the broken installation on the same machine)

**Comment by mezmac** [comment] 2023-01-14 17:30
Understood, thanks. I was caught off guard needing a domain for registration. Working on that now.

**Comment by xVet** [comment] 2023-01-31 16:34
@ravinsp @chalith should i close up the ticket here, as the issue seems solved in a different github issue?

**Comment by wojake** [comment] 2023-01-31 16:36
Ye, seems like you'd be fine closing this

**Comment by chalith** [comment] 2023-02-08 03:51
@xVet Thanks for the support. Closing the issue.

**Closed by chalith** 2023-02-08 03:51 UTC
