### ISSUE TITLE
How do I add the xahau fallback to my hosts? 

### ISSUE THREAD

**Issue by sojournease** [EvernodeXRPL/evernode-host#366] opened 2024-03-26 03:49 UTC
How do I add the fallback to my hosts? I have my hosts connected to a xahau node I'm renting ans dneed fallback entered yet not clear on exactly how to enter? Hosts running smooth and xahau payments being processed yet no ever rewards being sent.

I assume it's not having the fallback?

**Comment by du1ana** [comment] 2024-03-26 04:45
Closing as a duplicate of #365

**Closed as completed by du1ana** 2024-03-26 04:45 UTC
