### ISSUE TITLE
Installed failed reinstalled lost 500erv but it has been paid

### ISSUE THREAD

**Issue by prodevr01** [EvernodeXRPL/evernode-host#338] opened 2024-02-24 00:46 UTC
during the installation i transfred the XAH and the evers.
The installation failed, tried a coup of reinstalls the kept faining on the last install advised their was no evers.

rEZ9CVEfppfjm3ViCcyaD42judExCL5Bd3 when checking out the address I can see the payment.
https://xahau.xrplwin.com/account/rEZ9CVEfppfjm3ViCcyaD42judExCL5Bd3

what r my options ?

**Comment by BimsaraFernando** [comment] 2024-03-19 08:13
Hi @prodevr01,
it seems like your host is up and running. If the issue is resolved, please close the issue.

After the latest Evernode Installer update release we have improved the installation script with bug fixes. (https://github.com/EvernodeXRPL/evernode-host/issues/70#issuecomment-1976031300)  
If you are transferring the host registration, please follow the transfer guide (https://docs.evernode.org/en/latest/hosts/maintenance.html#transfer-the-host-registration )

**Comment by BimsaraFernando** [comment] 2024-06-10 08:30
Hi @prodevr01 ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.

**Closed as completed by BimsaraFernando** 2024-06-10 08:30 UTC
